### PR TITLE
Fixes #46 (depends on assertj-assertions-generator #129)

### LINKED ISSUE #46: Assertions are not generated for package protected classes
When I update my maven build to use version 2.1.0 of the `assertj-assertions-generator-maven-plugin` the build fails because some assertions were not generated. All affected classes are package protected classes, e.g.

```java
final class MyClass {
  // contents of the class omitted
}
```

The assertion reports lists the affected classes in this section:

```
No custom assertions files generated for the following input classes as they were not found:
```

Using version 2.0.0 the assertions for the package protected classes are generated.

Thus, I cannot update to version 2.1.0 because my tests will no longer compile. Increasing the visibility of the classes to `public` just be make the generator plugin work is not an option.

### PR DESCRIPTION
**Pull request by remibantos**
Add a new option named includePackagePrivateClasses to collect package private classes when true, false by default.

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Thanks @remibantos, I will review your PR at the end of month! (I'm taking some time off soonish) 
Ping me if I don't.

**Comment by remibantos** [comment]
Hi @joel-costigliola,
As promised, I come back to you regarding this PR (& the other one related)
Thanks

**Comment by joel-costigliola** [comment]
Looks good, once https://github.com/joel-costigliola/assertj-assertions-generator/pull/130 is integrated, I'll merge this one.

**Comment by joel-costigliola** [comment]
Integrated thanks @remibantos !

I have released the plugin (version 2.2.0), should be in maven central in a few hours.

**Comment by remibantos** [comment]
closed, already merged

**Pull request closed without merging**
